#!/bin/bash
systemctl stop telescope-pi 2> /dev/null
systemctl stop openfocuser 2> /dev/null
systemctl stop var-run-sdp.path 2> /dev/null
systemctl stop var-run-sdp.service 2> /dev/null
systemctl disable telescope-pi 2> /dev/null
systemctl disable openfocuser 2> /dev/null
systemctl disable var-run-sdp.path 2> /dev/null
systemctl disable var-run-sdp.service 2> /dev/null
